### ISSUE TITLE
Возможность использовать afterScript для выполнения действий после HTTP-запроса

### ISSUE THREAD

**Issue by nofuture17** [lamoda/gonkey#103]
Я бы хотел добавить afterScript по аналогии с beforeScript для того, что бы обновить materialised views  перед dbQuery. На данный момент обновить их можно использовать beforeScript и dbQuery во втором тесте, но это костыль и делает тесты менее очевидными.

**Comment by keyclaim** [comment]
Задачу можно закрывать
