### ISSUE TITLE
Добавить поле описания теста и отображать его в результатах

### ISSUE THREAD

**Issue by keyclaim** [lamoda/gonkey#147]
Добавить необязательное поле description в описание теста.
При отображении поля description (в output и allure report) должны учитываться переносы строки
```
- name: Название теста
   description: Описание теста
```
В случае если тест параметризован его также можно указать на уровне отдельного case
```
cases:
  - requestArgs:
    ..
    responseArgs:
    ..
    description:
```

**Comment by Mania-c** [comment]
https://github.com/lamoda/gonkey/pull/151
