### ISSUE TITLE
Http only endpoint testing

### ISSUE THREAD

**Issue by avgur** [lamoda/gonkey#17]
In case destination service hosted using https endpoint it is impossible to use gonkey command line, because gonkey console uses hard coded http schema.

**Comment by What-If-I** [comment]
Currently `http://` prefix is always prepended to the host name. But allowing to use `https://` schema should be quite straightforward. I'll look into it this week. Feel free to submit a pull request if you want.

**Comment by avgur** [comment]
Created pull request
