### ISSUE TITLE
Одновременная поддержка redis и postgres

### ISSUE THREAD

**Issue by VladimirStepanovRmr** [lamoda/gonkey#184]
Привет! Нужно сразу наполнять postgres и redis, но сейчас возможно выбрать только одно хранилище. Планируется ли такое дополнение?

**Comment by leorush** [comment]
О, тут надо будет много изменений, помимо этого в фикстурах и в запросах, нужно будет указывать к какой именно базе они применяются. Пока выход - готовить базу, которая не проверяется в тестах, отдельно.

**Comment by VladimirStepanovRmr** [comment]
Спасибо) закрываю тред

**Comment by leorush** [comment]
Как пожелание для развития - вполне, я думаю что в дальнейшем можно будет реализовать.
