### ISSUE TITLE
Оборачивать каждый тест в сабтесты

### ISSUE THREAD

**Issue by fetinin** [lamoda/gonkey#187]
Проблема следующая. При запуске тестов Gonkey сливает их все в одну кашу. Go test runner считает все тесты как один большой тест и все ошибки и логи по тестам сливаются.
Эта можно частично решить тем что каждый блок тестов или даже каждый тестовый файл заводится в коде отдельным тестом. Но это неудобно.
<img width="699" alt="image" src="https://user-images.githubusercontent.com/16325204/194596463-ccb3c0ad-c51f-4522-a0f8-695028e0b4e9.png">

Предлагаю на каждый тест оборачивать в testing.T.Run() чтобы test runner понимал что каждый тест в .yaml файле это отдельный тестовый сценарий. 

До:
[Screen Recording 2022-10-07 at 19.00.35.webm](https://user-images.githubusercontent.com/16325204/194600980-69eb5d2a-00d3-4b34-bc73-1737686d2a65.webm)

После:
[Screen Recording 2022-10-07 at 18.57.53.webm](https://user-images.githubusercontent.com/16325204/194601120-3819b4fb-a662-4eb8-a4fa-5fb897e5fad9.webm)

**Comment by What-If-I** [comment]
@leorush @keyclaim @luza @vitkarpenko напишите ваше мнение. Если никто не видит проблем, то оформлю PR.

**Comment by luza** [comment]
Очень круто, если получится так сделать.

**Comment by keyclaim** [comment]
Это очень-очень хорошо. 
Особенно в сочетании с https://github.com/lamoda/gonkey/pull/151
