### ISSUE TITLE
Variables usage

### ISSUE THREAD

**Issue by avgur** [lamoda/gonkey#20]
Is it possible to use inserted row id from the db fixture inside the web request test?
Can you, please, provide example how to insert record into db and than test http request to fetch data by inserted id?

**Comment by luza** [comment]
No, that's not supported.

Using database auto incrementing ID for any purpose outside the database is a bad practice, as such ID is highly implementation-dependant and does not guarantees uniqueness on the inter-services scale.

**Comment by avgur** [comment]
Ok, got it
Maybe it is possible to store property from the first test in scenario as variable and then use it in the next test in the same scenario? That way i will be able to login and remember jwt token in the first test and then use jwt token for the second test...

**Comment by codercms** [comment]
@avgur why just don’t use UUID or fixed ID value while you inserting data to DB? So you can easily use ID that you know in tests.
