### ISSUE TITLE
Collision in field and table name causes issues

### ISSUE THREAD

**Issue by luza** [lamoda/gonkey#21]
Faced an error `function row_to_json(integer) does not exist` on loading fixture to the table, one  column of which named the same as the table.

Happens because under the hood Gonkey constructs following query:
```
INSERT INTO "level" ("brand_id", "cashback_factor", "level") VALUES (6577, 0.05, 2) RETURNING row_to_json("level")
```

Possible solution is to stop using `RETURNING row_to_json()` in favour of `RETURNING *` and to scan result into the struct (adopt one of existing libraries for this job).

**Comment by What-If-I** [comment]
Would it help if we'll give a table some unique alias with `AS`?

**Comment by luza** [comment]
Hm, good point. That might work too.

**Comment by What-If-I** [comment]
It did :)
