### ISSUE TITLE
Как протестировать получение файла?

### ISSUE THREAD

**Issue by batazor** [lamoda/gonkey#231]
У меня есть тест который проверяет получение файла,в моей кейсе достаточно отличать статус ответа 200/404

```
response:
  200:

responseHeaders:
  200:
    Content-Type: "image/jpeg"
```

Однако такой вариант не срабатывает и падает, есть способ проигнорить `body` в ответе?

```
Response:
     Status: 200 OK
       Body:
������	
2!!22222222222222222222222222222222222222222222222222�������"��������������	
���}�!1AQa"q2��#B��R��$3br�	
```

**Comment by lechefer** [comment]
Если убрать блок с "response" и оставить только "responseHeaders" не будет работать случаем?

**Comment by lechefer** [comment]
Для "response" он всегда сравнивает тела

**Comment by Alexey19** [comment]
`
  response:
    200: "$matchRegexp(.*)"
  responseHeaders:
    200:
      Content-Type: "image/jpeg"
`

**Comment by batazor** [comment]
Да, вариант с `"$matchRegexp(.*)"` думаю приемлем
