### ISSUE TITLE
Assert response headers and cookies

### ISSUE THREAD

**Issue by amuttsch** [lamoda/gonkey#28]
Hi,

is it possible to assert the headers and cookies in the response? Using `response` I can only define a status code and a body.

Thanks for any hints!

**Comment by luza** [comment]
Hi, there is no such a feature at the moment. As you noticed, currently status code and body are the only subjects to test in response.

**Comment by amuttsch** [comment]
Thanks for the quick reply. Are there plans to support such a feature in the future?

**Comment by luza** [comment]
Yes, definitely. Converted the issue into a feature request.

**Comment by luza** [comment]
Checking response headers added in #45
