### ISSUE TITLE
Gonkey не дожидается обращений в моки после получения response

### ISSUE THREAD

**Issue by keyclaim** [lamoda/gonkey#41]
Столкнулись с такой ситуацией что сервис не всегда может дожидаться результатов запросов в свои зависимости.
Как следствие проверка мока calls = <value> возвращает ошибку.

Проблему можно решить явным ожиданием после request добавив еще одну паузу.
Также можно добавить в мок timeout  + ожидание заданного количества calls, что более предпочтительно.

**Comment by luza** [comment]
Уже касались этой темы ранее.

Мое мнение: нужно в тестах избавляться от параллельности, чтобы все вызовы были синхронные и последовательные.

Для этого нужно:
1) в gonkey добавить обертку на `go`, которая запускает горутину.
2) в приложении все прямые вызовы `go` заменить на вызов обертки
3) при запуске тестов перепределять обертку над `go` так, чтобы она не создавала горутину, а выполняла код синхронно

**Comment by keyclaim** [comment]
Спасибо за идею, будем пробовать
