### ISSUE TITLE
Если передать db, но не передать DbType, тест паникует

### ISSUE THREAD

**Issue by finnan444** [lamoda/gonkey#73]
В документации нигде параметр не описан + паника не самый лучший вариант выхода
Предлагаю:
1. Добавить в документацию `DbType`, раз он обязательный, если передаем `db`.
2. Изменить сигнатуру ответа `fixtures.NewLoader` - возвращать ошибку а-ля
`func NewLoader(cfg *Config) (Loader, error) {}`. Соответственно выше можно ошибку поймать и вызвать например `t.Fatal(err)`
Также можно добавить метод к структуре `fixtures.Config` метод `func (config Config) validate() error {}` который будет возвращать ошибку, если `DB == nil` или `DbType` неизвестный.

**Comment by luza** [comment]
Я пока совсем не понял, что за `DbType`.

Можете показать пример вызова, который завершится паникой?

**Comment by finnan444** [comment]
```
runner.RunWithTesting(t, &runner.RunWithTestingParams{
		Server:   srv,
		TestsDir: "./cases",
		DB:       db,
		//DbType:      fixtures.Postgres,
		FixturesDir: "./fixtures",
	})
```
паника [ожидаемая](https://github.com/lamoda/gonkey/blob/master/fixtures/loader.go#L57)

**Comment by luza** [comment]
Теперь все ясно.

**Comment by luza** [comment]
Нужно по возможности детектить движок базы самостоятельно.

Если детектить его невозможно, то принимать параметр DbType, который по умолчанию должен быть Postgres для обеспечения обратной совместимости. Добавить DbType в документацию.

Если передан неподдерживаемый DbType, то паниковать. Паника здесь подходит больше, чем возврат ошибки, потому что исправление нужно делать в вызывающем коде - без такого исправления запуск тестов вообще не имеет смысла.
