### ISSUE TITLE
Добавить возможность очищать таблицы перед выполнением каждого теста

### ISSUE THREAD

**Issue by keyclaim** [lamoda/gonkey#83]
В настоящий момент мы никак не можем задать пустую таблицу (очистить отдельную таблицу/всю базу или задать пустую таблицу через фикстуру).

Есть три варианта как это можно было бы сделать:
1) всегда чистить все таблицы базы вперед прогоном тестов внутри одного yaml файла
- очистка таблиц будет только в рамках одного yaml
- все под капотом
2) добавить параметр в runner и опираясь на него чистить все таблицы базы перед каждым исполнением теста 
- придется запускать в отдельном ране флоу тесты
- еще один параметр в раннере
3) добавить нотацию фикстур возможность обозначать таблицы которые должны быть пустыми
- все под капотом
- очистка задается явным образом

Для начала хотелось бы обсудить, какой из вариантов наиболее подходящий

**Comment by Alexey19** [comment]
У себя в коде мы решили каждый yaml обрабатывать отдельной функцией типа так
```
func TestDeleteDataApi(t *testing.T) {
	runSpecificTest(t, "test_delete_data.yaml")
}

func TestDeleteDataErrorsApi(t *testing.T) {
	runSpecificTest(t, "test_delete_data_errors.yaml")
}

func TestGetDataWithFilterApi(t *testing.T) {
	runSpecificTest(t, "test_get_data_with_filter.yaml")
}
```
а в функции в реальности сносим все таблицы сервиса и пересоздаем таблицы (с помощью миграций). Это позволяет получить сервис без сайд-эффектов других тестов (понимаю, что это не всегда прям хорошо).

**Comment by keyclaim** [comment]
Как оказалось текущая версия  Gonkey позволяет выполнять очистку таблиц если в фикстурах передавть пустой список.

`tables:
    codes: []`
  
  Вопрос более не актуален :)

**Comment by keyclaim** [comment]
согласен, поторопился
текущие возможности обязательно нужно задокументировать

**Comment by keyclaim** [comment]
Добавили описание в #92
