### ISSUE TITLE
Возможность помечать отдельный тест статусом skipped/broken etc

### ISSUE THREAD

**Issue by keyclaim** [lamoda/gonkey#90]
Нужно больше контроля над запуском тестов.
Возможность запускать отдельный файл хорошо, но куда удобней иметь переключатель в самом тесте.

Предлагаю также помечать тесты которые мы хотим пропустить этими же статусами и не выполнять их.
Так мы сможем
- broken если в текущий момент их нельзя удалить но нужно пропускать
- skipped если нам нужно пропустить тест

Мы пробрасывает результат в поле  status в AllureReport и там уже предполагается набор состояний
![tab_graphs](https://user-images.githubusercontent.com/16463570/118792697-93ddd900-b8a0-11eb-9c2b-156f7aac4794.png)

**Comment by leorush** [comment]
Также полезным может быть спец-статус позволяющий запустить только один тест. Полезно для отладки.
Ставим тесту `status: solo` и все остальные тесты автоматически получают статус skipped

**Comment by keyclaim** [comment]
мне больше нравится нотация `focus` в ginkgo
пример вот тут https://onsi.github.io/ginkgo/#focused-specs

**Comment by leorush** [comment]
Ну название не существенно ) Главное можно будет добавить в текущую реализацию.

**Comment by keyclaim** [comment]
@Cdayz нужно ли завести отдельный Issue?

**Comment by Cdayz** [comment]
@keyclaim думаю нет, реализуем в рамках этого issue+pr

**Comment by maximdanilchenko** [comment]
Как развитие статуса focus - может быть полезным сделать что-то типа маркировки тестов, как сделано в pytest например. Чтобы можно было запускать тесты, которые промаркированы определенным тегом/тегами. Ну это точно отдельный issue конечно.

**Comment by leorush** [comment]
> Как развитие статуса focus - может быть полезным сделать что-то типа маркировки тестов, как сделано в pytest например. Чтобы можно было запускать тесты, которые промаркированы определенным тегом/тегами. Ну это точно отдельный issue конечно.

Теги это другое. Тоже нужно, но их может быть много - один тест может относиться сразу к нескольким тегам.

**Comment by keyclaim** [comment]
Если строго подходить к вопросу, то и focus не является  status - что не совсем корректно, так как status мы пробрасываем в allure report.
Теги нам нужны разве что как лейблы в allure report.
Если говорить о тегах как параметрах запуска, в самом go есть build tags и ими можно обмазаться на уровне кода, если хочется запускать группы тестов.

Мы можем добавить в раннер входной параметр со слайсом тэгов и использовать их для запуска групп тестов и тогда status focus  не будет нужен. Также будет неплохо эти теги пробрасывать в allure как labels.

Предлагаю в таком случае с focus притормозить @Cdayz

**Comment by luza** [comment]
Мне нравится идея с broken и skipped, но не нравится с focus, равно как и тегами.

Я напомню, что файл - это в gonkey минимальная запускабельная единица, потому что тесты внутри файла - это сценарий, где каждый последующий тест может опираться на результат работы предыдущих в этом файле, а также на фикстуры, загруженные ранее. А если тесты в файле - не сценарий, то зачем ты их написал в один файл? :)

Поэтому отметить какой-то тест в середине файла как focus - это противоречит паттерну и скорее всего будет неполезно. Равно как и запуск каких-то тестов, отфильтрованных по тегам, из середины файла.

Я бы предложил предусмотреть возможность тегать файлы. А также, возможно, поискать более удобный способ запускать файлы точечно (хотя сам пользуюсь GONKEY_FILE_FILTER и мне норм).

**Comment by keyclaim** [comment]
Также придерживаюсь этой парадигмы. Но я и не знал про `GONKEY_FILE_FILTER`!)
Будет задача на апдейт readme :) Этого действительно достаточно для запуска единичных файлов.
Тегать файлы поддерживаю.

Если говорить об иерархии, то у нас в целом проблемы с отчетами когда дело касается флоу-тестов.
Тестировать флоу в рамках одного файла в целом не проблема, но для отчетов это все так же отдельные тесты, так как там поле `name` будет ключом. 
Похоже нужна внедрить сущность флоу тестов, чтобы name все также был один, а вот результаты записывались по каждому шагу. В allure это можно в  steps записывать.

В общем я это хорошенько обдумаю и опишу.
